<?php

namespace Aamant\ConfigurableAttributesBundle\Repository;

/**
 * AttributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributeDefinitionRepository extends \Doctrine\ORM\EntityRepository
{
}
