<?php

namespace Aamant\ConfigurableAttributesBundle\Repository;

/**
 * AttributeValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionRepository extends \Doctrine\ORM\EntityRepository
{
}
